spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: true

redis:
  host: 192.168.1.19
  port: 7001
  password:

server:
  port: 8081